CREATE TABLE land_record
(
   "VALUE"  NUMBER NOT NULL DEFAULT 0,
   "OWNER"  VARCHAR(256) NOT NULL,
   "YEAR"   NUMBER NOT NULL DEFAULT 2023,
   BOOK     NUMBER NOT NULL DEFAULT 1,
   "ADDRESS" VARCHAR(256) NOT NULL,
   ID       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

create table users(
	username varchar_ignorecase(50) not null primary key,
	password varchar_ignorecase(500) not null,
	enabled boolean not null
);

create table authorities (
	username varchar_ignorecase(50) not null,
	authority varchar_ignorecase(50) not null,
	constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);